### ISSUE TITLE
Switch to `carpentries/sandpaper`

### ISSUE THREAD

**Issue by milanmlft** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#1]
If https://github.com/carpentries/sandpaper/pull/585 gets merged in, we won't need our own fork of `{sandpaper}` anymore.

### Changes needed

- [ ] Remove `sandpaper: HealthBioscienceIDEAS/sandpaper@IDEAS` from the `config.yaml` file

### Dependencies

- [x] https://github.com/carpentries/sandpaper/pull/585

**Comment by mxochicale** [comment]
Thanks @milanmlft, let us know when your PR is merged to address this one!

**Comment by milanmlft** [comment]
Will do, note that this won't change anything to the way the lesson is built. It just means I'll have one less repo to maintain ;)

**Comment by mxochicale** [comment]
Seems updates are coming https://github.com/carpentries/sandpaper/pull/585#issuecomment-2167597566

**Comment by mxochicale** [comment]
Closing this one as PR merge from carpentries seems to be slow. 
@milanmlft  please feel free to open it and point out what needs to be done!

Thanks

**Comment by milanmlft** [comment]
https://github.com/carpentries/sandpaper/pull/585 got merged in, so we can move this forward. Same as for https://github.com/HealthBioscienceIDEAS/microscopy-novice/issues/63

**Comment by milanmlft** [comment]
I'm planning to remove https://github.com/HealthBioscienceIDEAS/sandpaper soon, so in order to keep this lesson building, just need to remove the following line from `config.yaml`:
https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/blob/b188e162c72f1777748d32bbbff79070a333bd3b/config.yaml#L81

**Comment by davecash75** [comment]
Thanks @milanmlft - I've been able to make new sandpaper lessons which don't use the IDEAS repository, so I will re-open and make the changes.
