### ISSUE TITLE
Converting DICOM images to nifti `Error: exception occurred during image IO. Exception: std::expedition`

### ISSUE THREAD

**Issue by mxochicale** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#10]
We are trying to convert [DICOM](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/issues/7#issuecomment-2135013603) images to nifti in ITK-snap but I got this error when using Save Image `1-175.gz` with File Format `NiFTi`: Error: exception occurred during image IO. Exception: std::expedition

I am also trying `Convert3D` https://sourceforge.net/p/c3d/wiki/Home/ with some details here on the [conversion](https://groups.google.com/g/itksnap-users/c/69Qs8ey-bOo). However, got the following errors
```
 ./c3d -dicom-series-list 3_000000-CT_Lung_30_B31f-61322 1.3.6.1.4.1.14519.5.2.1.144951524860072109435466295249203161322.33512512 -o test.nii.gz
SeriesNumber	Dimensions	NumImages	SeriesDescription	SeriesID
3 	512x512x10	10	CT Lung  3.0  B31f	1.3.6.1.4.1.14519.5.2.1.144951524860072109435466295249203161322.33512512
Exception caught of type 16ConvertException
  Exception detail: Unable to read image 1.3.6.1.4.1.14519.5.2.1.144951524860072109435466295249203161322.33512512; IO factory can not create IO object.
```
Similar issues happen with demo-data `CT_subject_1_dicom/`

**Comment by mxochicale** [comment]
Other options to convert DICOM to nifti:
* `dicom2nifti`  https://www.kaggle.com/code/rinichristy/dicom-to-nifti-conversion-using-nibabel https://medium.com/@pmegne/dicom-to-nifti-conversion-dc436c0b5fa6
* https://github.com/rordenlab/dcm2niix
* https://neuroimaging-cookbook.github.io/recipes/dcm2nii_recipe/

**Comment by zsenousy** [comment]
I do the conversion from the ITK-snap by clicking 'File' --> 'Save image' --> rename image and choose format as 'NiFTI'

**Comment by mxochicale** [comment]
I think the issue is with itk-snap for Linux-gcc64: 
![Screenshot from 2024-05-30 12-51-56](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/assets/11370681/a24e3955-a5e3-49e6-bcf1-a1d91def6df8)

One suggestion in the [forum](https://groups.google.com/g/itksnap-users/c/O1Xv91S2K3k) is to use another external tool , so `dicom2nifti` seems to work (having some nice [features (compression, reorient, --resample, etc.)](https://github.com/icometrix/dicom2nifti)):

```
from pathlib import Path 
import dicom2nifti 
dicoms = Path("~/3_000000-CT_Lung_30_B31f-61322")
dicom2nifti.convert_directory(dicoms, ".", compression=True, reorient=True)
```

**Comment by zsenousy** [comment]
If you could solve the issue and do it from inside ITK-snap that would be great. This will alleviate any burden on students during learning.

**Comment by mxochicale** [comment]
closing in favour of https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/issues/15
