### ISSUE TITLE
What can we do with excercise 3 - demons registration

### ISSUE THREAD

**Issue by thompson318** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#12]
Take Jamie's code and tidy it up. Can we do that in the time left?

**Comment by zsenousy** [comment]
Hi @thompson318 and @mxochicale,

Please check some progress for breaking down the demons image registration code into steps [exercise 3 steps](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/blob/4-excercise4/episodes/excthreesteps.Rmd). The code has minor modification for output 3 different images in one pane.

Talk to you next week for updates and reviewing.

**Comment by mxochicale** [comment]
Thanks @zsenousy can you please create a new branch derived from branch 4-excercise4  (e.g. `git checkout 4-excercise4` and git checkout -b 12-exercise3) and send PR to us (@thompson318 , @mxochicale) to then request review to Dave. Thanks, Miguel

**Comment by thompson318** [comment]
We need to look at the demons code and discuss with @jamie-mcclelland and @davecash75 what the main objectives for this exercise are. Currently there's a lot of code dedicated to getting images displayed with matplotlib. If we want to focus on understanding demons registration we could move all the display code to separate classes or functions that we just import at the top then call. Alternatively if it's important that the students understand how to use matplotlib we just need to reformat stuff. At the moment the code snippets are very long with lots of comments. Would be better to have shorter snippets with the explanatory text in the main text body.

**Comment by thompson318** [comment]
Target: 
A single window with two sub-plots: left figures 1, 2, and 3 (source, target, warped). right figures 4 and 5 (deformed and update fields).
Use matplot lib's event loop to allow the students to interactively change the view. (high priority)
Longer term we can have some GUI elements to change parameters.

Work through pdf document to make sure application suits student needs.

**Comment by zsenousy** [comment]
Exercise 3 Summary:

- Initial display of 5 subplots has been created (Source, target, warped, deformation field and update field) and then removed later as requested by @jamie-mcclelland.
- live update function has been created to plot a figure with 3 subplots (warped image, deformation field, and update field) and a top message to show text information. This to show live update of registration process without the need to pop up multiple figures during each level and without the need to close/open new figure for each level as requested by @davecash75.
- A final display with 3 subplots (1- navigation between source, target, warped images, 2- navigation between deformation field and Jacobian and 3- difference image). This final display is only shown after registration levels end as requested by @jamie-mcclelland.
