### ISSUE TITLE
Reviewing Rdm files with `*.md` files withing github repository?

### ISSUE THREAD

**Issue by mxochicale** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#14]
Previewing episodes is done via R with `sandpaper::build_lesson()` which require users to have installed R. 

@milanmlft  Wondering if we can have a markdown file (*.md) that renders text and figures of the `*.Rdm` for just content review purposes (without the need to install R or download anything) ?

**Comment by milanmlft** [comment]
`sandpaper` has a GitHub actions bot that comments on any PR with a preview of `Rendered Changes`, see for example here: https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/pull/5#issuecomment-2112371887, specifically the line
> 🔍 Inspect the changes: [`md-outputs..md-outputs-PR-5` (compare)](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/compare/md-outputs..md-outputs-PR-5)

Isn't this what you're asking for? Or am I misunderstanding?
