### ISSUE TITLE
Episode titles and learing objectives.

### ISSUE THREAD

**Issue by thompson318** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#2]
Split content into individual episodes for the three days. These should have:

Title

List of learning objectives + questions (i.e. the content of the 'overview' box at the top of each lesson - example from another course: https://swcarpentry.github.io/python-novice-gapminder/03-types-conversion.html)

* [ ] #3

**Comment by mxochicale** [comment]
Duplicated and closing of favour of  https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/issues/3#issuecomment-2130058978
