### ISSUE TITLE
What data should we use.

### ISSUE THREAD

**Issue by thompson318** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#7]
Current data is opensource but uses a head and neck scan which is potentially not anonymous.

- [ ] Data is freely available.
- [ ] We have ethical approval to use data for this purpose.
- [ ] Cancer imaging archive For most data sets except the head no agreement is required.
- [ ] DRI - labs data set - lung images with manually annotated landmarks.
- [ ] https://openneuro.org/
- [ ] https://med.emory.edu/departments/radiation-oncology/research-laboratories/deformable-image-registration/index.html
- [ ] https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2
- [ ] We want it in DICOM format, so we can include the conversion of DICOM to Nifti.
- [ ] https://openneuro.org/datasets/ds001421/versions/1.4.1

**Comment by jamie-mcclelland** [comment]
i've had a quick look on tcia and this dataset looks like it will be perfect:

https://www.cancerimagingarchive.net/collection/ct-vs-pet-ventilation-imaging/

it's lung images - has several different images per patient (4dct, breath hold ct, pet and accompanying ct) - some of which should already be aligned with each other and could be used for the first practical with no further processing. it has data from 20 patients, but we'll only need to use data from one of them for the first exercises, and suggest maybe using the two breath hold cts for the practical 
the dataset also has lots of potential to be used for the later practical session where we actually go through registering some images (its very similar to the dir-lab data used in my coursework this year, but in some ways even better)

@mxochicale - could you download this dataset and have a look at it and see if it looks suitable for the exercises? let me know if you have any questions about it or want to discuss anything further before we next meet.

**Comment by mxochicale** [comment]
@jamie-mcclelland Just downloaded [DICOM](https://www.cancerimagingarchive.net/collection/ct-vs-pet-ventilation-imaging/) data! For breath hold cts, I think we can focus with CT-PET-VI-02 (which contain "BHCT scans for CT-PET-VI-02 & CT-PET-VI-03, showing very little motion between inhale and exhale"). Data paths look like these:
```
/CT-PET-VI-02$ tree -d 
.
├── 1000.000000-PET SUV Factors-26496 [1 item, with size 42.1 kB]
├── 3.000000-CT Lung  3.0  B31f-61322  [175 items, totalling 92.4 MB]
├── 4.000000-Galligas Lung-03537 [159 items, totalling 51.5 MB]
├── 5.000000-Thorax Insp  2.0  B70f-29873 [167 items, totalling 88.1 MB]
├── 7.000000-Thorax Exp  2.0  B70f-73355 [167 items, totalling 88.1 MB]
└── 8.000000-RespLow  2.0  B30s  80  Ex - 100  In-44317 [810 items, totalling 426.9 MB]
6 directories

FYI:
/CT-PET-VI-03$ tree -d
.
├── 06-25-1996-RTRTRespLowBreathRateRNS Adult-43080
│   ├── 1000.000000-PET SUV Factors-06580
│   ├── 3.000000-CT Lung  3.0  B31f-08354
│   └── 4.000000-Galligas Lung-15379
└── 06-25-1996-RTRTRespLowBreathRateRNS Adult-87093
    ├── 5.000000-Thorax Insp  2.0  B70f-42000
    ├── 7.000000-Thorax Exp  2.0  B70f-45310
    └── 8.000000-RespLow  2.0  B30s  80  Ex - 100  In-54790

```
So, I think we can start exercise 4 with DICOM data "CT-PET-VI-02/3.000000-CT Lung  3.0  B31f-61322" but feel free to bring further suggestions:

![Screenshot from 2024-05-28 12-41-08](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/assets/11370681/1f7a33cc-bbf2-45cd-9737-4c3c2dfef847)

**Comment by mxochicale** [comment]
Some options to share data `├── 3.000000-CT Lung  3.0  B31f-61322  [175 items, totalling 92.4 MB]` for exercise 4:
* Moodle 
* Tiny links pointing to share-drive or google-drive
* learnupon.com/
* Zenodo

**Comment by mxochicale** [comment]
I don't think we have decided where to host data for exercise 4 that might also contain other data for demons registration, so let's reopen this one! 

Essentially we would like to compressed the following files for exercise 4:

We recommend using the BHCT scans for participants CT-PET-VI-02 and CT-PET-VI-03 showing very little motion between inhale and exhale (for PET scan and accompanying CT scan), and BHCT scans for participants CT-PET-VI-05 and CT-PET-VI-07 (the inhale and exhale CT scans), where 05 has a different number of slices between the inhale and exhale:

CT-PET-VI-02
CT-PET-VI-02$ tree -d
.
└── 05-28-1996-RTRTRespLowBreathRateRNS Adult-05441
    ├── 3.000000-CT Lung  3.0  B31f-61322
    ├── 4.000000-Galligas Lung-03537
CT-PET-VI-03
/CT-PET-VI-03$ tree -d
.
├── 06-25-1996-RTRTRespLowBreathRateRNS Adult-43080
│   ├── 3.000000-CT Lung  3.0  B31f-08354
│   └── 4.000000-Galligas Lung-15379
CT-PET-VI-05
CT-PET-VI-05$ tree -d
.
└── 12-10-1996-RTRTRespLowBreathRateRNS Adult-37585
    ├── 5.000000-Thorax Insp  2.0  B70f-45546
    ├── 7.000000-Thorax Exp  2.0  B70f-31579
CT-PET-VI-07
/CT-PET-VI-07$ tree -d
.
└── 02-14-1997-RTRTRespLowBreathRateRNS Adult-80512
    ├── 5.000000-Thorax Insp  2.0  B70f-20440
    ├── 7.000000-Thorax Exp  2.0  B70f-03567
