### ISSUE TITLE
 "The server you have tried to access is undergoing maintenance. Please try again later." for `NBIA/Downloading+TCIA+Images` in Windows

### ISSUE THREAD

**Issue by mxochicale** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#9]
https://wiki.cancerimagingarchive.net/display/NBIA/Downloading+TCIA+Images

**Comment by mxochicale** [comment]
@zsenousy  Link to download NBIADataRetriever_4.4 for windows is working now https://cbiit-download.nci.nih.gov/nbia/releases/ForTCIA/NBIADataRetriever_4.4/NBIA%20Data%20Retriever-4.4.msi

**Comment by zsenousy** [comment]
Thanks, @mxochicale I am aware of this. Feel free to close the issue.
